// <auto-generated />
using System;
using FlowSpace.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowSpace.Persistence.Migrations
{
    [DbContext(typeof(FlowSpaceDbContext))]
    [Migration("20260724104830_AddGanttScheduleHistoryAndDuration")]
    partial class AddGanttScheduleHistoryAndDuration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowSpace.Domain.Entities.TaskItem", b =>
                {
                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMilestoneTask")
                        .HasColumnType("boolean");
                });

            modelBuilder.Entity("FlowSpace.Domain.Entities.TaskScheduleHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("OldStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OldDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NewStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NewDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("TaskId", "ChangedAt");

                    b.ToTable("TaskScheduleHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
